name: Update pre-commit

on:
  workflow_dispatch:

permissions:
  pull-requests: write

jobs:
  pre-commit-update:
    name: Update pre-commit
    uses: rmartin16/.github-beeware/.github/workflows/pre-commit-update.yml@update-pre-commit
    secrets: inherit
